version: "3.8"

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    environment:
      - SERVICE_URL_DUPLICATI_8200
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Berlin}
      - SETTINGS_ENCRYPTION_KEY=${SERVICE_PASSWORD_ENCRYPT}
      - DUPLICATI__WEBSERVICE_PASSWORD=${SERVICE_PASSWORD_WEB}
    volumes:
      - /var/lib/docker/volumes:/source:ro
      - duplicati-config:/config
      - duplicati-backups:/backups
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8200"]
      interval: 2s
      timeout: 10s
      retries: 15
