version: '3.9'
services:
  minidlna:
    image: vladgh/minidlna
    environment:
      - MINIDLNA_FRIENDLY_NAME=${FRIENDLY_NAME}
      - MINIDLNA_MEDIA_DIR=/media
    volumes:
      - type: bind
        source: ${ABSOLUT_PATH_TO_MEDIA}
        target: /media
        read_only: true
    network_mode: "host"
    restart: always