version: '3.9'
services:
  minidlna:
    image: vladgh/minidlna
    environment:
      - MINIDLNA_FRIENDLY_NAME=${FRIENDLY_NAME}
      - MINIDLNA_MEDIA_DIR=/media
    volumes:
      - ${ABSOLUTE_PATH_TO_MEDIA}:/media
    network_mode: "host"
    restart: always